//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrier
    {
        public Carrier()
        {
            this.Lading = new HashSet<Lading>();
            this.Route = new HashSet<Route>();
        }
    
        public int CarrierID { get; set; }
        public bool Enabled { get; set; }
        public string Name { get; set; }
        public string CarrierType { get; set; }
        public string Addr { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string OKDP { get; set; }
        public string OKPO { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string Note { get; set; }
        public string АвтоРегНомер { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleBrand { get; set; }
        public Nullable<decimal> MaxVol { get; set; }
        public Nullable<decimal> MaxWg { get; set; }
    
        public virtual CarrierType CarrierType1 { get; set; }
        public virtual ICollection<Lading> Lading { get; set; }
        public virtual ICollection<Route> Route { get; set; }
    }
}
