//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoTy
    {
        public CoTy()
        {
            this.ShipCont = new HashSet<ShipCont>();
        }
    
        public string CoTy1 { get; set; }
        public string cocl { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
    
        public virtual ICollection<ShipCont> ShipCont { get; set; }
    }
}
