//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Order = new HashSet<Order>();
            this.Order1 = new HashSet<Order>();
        }
    
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string Addr { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public string Bank { get; set; }
        public string BIK { get; set; }
        public string CorrAcc { get; set; }
        public string SettAcc { get; set; }
        public string DepID { get; set; }
        public string DepName { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string OKDP { get; set; }
        public string OKPO { get; set; }
        public bool Enabled { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Order> Order1 { get; set; }
    }
}
