//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dest
    {
        public Dest()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int DestID { get; set; }
        public string Addr { get; set; }
        public string Phone { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW1From { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW1To { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW2From { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW2To { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW3From { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW3To { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW4From { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW4To { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW5From { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW5To { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW6From { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW6To { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW7From { get; set; }
        public Nullable<System.TimeSpan> DeliverySchW7To { get; set; }
        public Nullable<System.TimeSpan> WorkSchW1From { get; set; }
        public Nullable<System.TimeSpan> WorkSchW1To { get; set; }
        public Nullable<System.TimeSpan> WorkSchW2From { get; set; }
        public Nullable<System.TimeSpan> WorkSchW2To { get; set; }
        public Nullable<System.TimeSpan> WorkSchW3From { get; set; }
        public Nullable<System.TimeSpan> WorkSchW3To { get; set; }
        public Nullable<System.TimeSpan> WorkSchW4From { get; set; }
        public Nullable<System.TimeSpan> WorkSchW4To { get; set; }
        public Nullable<System.TimeSpan> WorkSchW5From { get; set; }
        public Nullable<System.TimeSpan> WorkSchW5To { get; set; }
        public Nullable<System.TimeSpan> WorkSchW6From { get; set; }
        public Nullable<System.TimeSpan> WorkSchW6To { get; set; }
        public Nullable<System.TimeSpan> WorkSchW7From { get; set; }
        public Nullable<System.TimeSpan> WorkSchW7To { get; set; }
        public string Note { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
