//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lading
    {
        public Lading()
        {
            this.Ship = new HashSet<Ship>();
        }
    
        public int LadingID { get; set; }
        public string WmsLadingID { get; set; }
        public System.DateTime DeliveryDT { get; set; }
        public Nullable<System.DateTime> LoadDT { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public short RouteID { get; set; }
        public string Note { get; set; }
        public string Gate { get; set; }
        public int Priority { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        public virtual Route Route { get; set; }
        public virtual ICollection<Ship> Ship { get; set; }
    }
}
