//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DmeEntities : DbContext
    {
        public DmeEntities()
            : base("name=DmeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Клиенты> Клиенты { get; set; }
        public DbSet<ДоставкаАдрес> ДоставкаАдрес { get; set; }
        public DbSet<ДоставкаДокумент> ДоставкаДокумент { get; set; }
        public DbSet<ДоставкаКонтакт> ДоставкаКонтакт { get; set; }
        public DbSet<ДоставкаОтправитель> ДоставкаОтправитель { get; set; }
        public DbSet<ДоставкаПолучатель> ДоставкаПолучатель { get; set; }
        public DbSet<ДоставкаСвФЛ> ДоставкаСвФЛ { get; set; }
        public DbSet<ДоставкаСвЮЛ> ДоставкаСвЮЛ { get; set; }
        public DbSet<ДоставкаСтрТабл> ДоставкаСтрТабл { get; set; }
        public DbSet<ДоставкаТаблДок> ДоставкаТаблДок { get; set; }
        public DbSet<ДоставкаФайл> ДоставкаФайл { get; set; }
        public DbSet<ДоставкаПараметр> ДоставкаПараметр { get; set; }
        public DbSet<Carrier> Carrier { get; set; }
        public DbSet<CarrierType> CarrierType { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<Dest> Dest { get; set; }
        public DbSet<Lading> Lading { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderDocRow> OrderDocRow { get; set; }
        public DbSet<OrderFactRow> OrderFactRow { get; set; }
        public DbSet<OrderNote> OrderNote { get; set; }
        public DbSet<OrderType> OrderType { get; set; }
        public DbSet<Partm> Partm { get; set; }
        public DbSet<Route> Route { get; set; }
        public DbSet<Ship> Ship { get; set; }
        public DbSet<ShipCont> ShipCont { get; set; }
        public DbSet<B2BUser> B2BUser { get; set; }
        public DbSet<CoTy> CoTy { get; set; }
        public DbSet<ExportDoc> ExportDoc { get; set; }
    }
}
