//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DmeEntities : DbContext
    {
        public DmeEntities()
            : base("name=DmeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<АктПриемкиАдрес> АктПриемкиАдрес { get; set; }
        public DbSet<АктПриемкиБухгалтер> АктПриемкиБухгалтер { get; set; }
        public DbSet<АктПриемкиГрузоотправитель> АктПриемкиГрузоотправитель { get; set; }
        public DbSet<АктПриемкиГрузополучатель> АктПриемкиГрузополучатель { get; set; }
        public DbSet<АктПриемкиДокумент> АктПриемкиДокумент { get; set; }
        public DbSet<АктПриемкиПоДокументам> АктПриемкиПоДокументам { get; set; }
        public DbSet<АктПриемкиПокупатель> АктПриемкиПокупатель { get; set; }
        public DbSet<АктПриемкиПоставщик> АктПриемкиПоставщик { get; set; }
        public DbSet<АктПриемкиПоФакту> АктПриемкиПоФакту { get; set; }
        public DbSet<АктПриемкиПредставители> АктПриемкиПредставители { get; set; }
        public DbSet<АктПриемкиРуководитель> АктПриемкиРуководитель { get; set; }
        public DbSet<АктПриемкиСписокАдрес> АктПриемкиСписокАдрес { get; set; }
        public DbSet<АктПриемкиСписокОснование> АктПриемкиСписокОснование { get; set; }
        public DbSet<АктПриемкиСписокПараметр> АктПриемкиСписокПараметр { get; set; }
        public DbSet<АктПриемкиСписокСтрОтклонения> АктПриемкиСписокСтрОтклонения { get; set; }
        public DbSet<АктПриемкиСписокХарактеристика> АктПриемкиСписокХарактеристика { get; set; }
        public DbSet<АктПриемкиСтороны> АктПриемкиСтороны { get; set; }
        public DbSet<АктПриемкиСтрОтклонения> АктПриемкиСтрОтклонения { get; set; }
        public DbSet<АктПриемкиФайл> АктПриемкиФайл { get; set; }
        public DbSet<ЗаказНаРазмещениеАдрес> ЗаказНаРазмещениеАдрес { get; set; }
        public DbSet<ЗаказНаРазмещениеДокумент> ЗаказНаРазмещениеДокумент { get; set; }
        public DbSet<ЗаказНаРазмещениеИтогТабл> ЗаказНаРазмещениеИтогТабл { get; set; }
        public DbSet<ЗаказНаРазмещениеОснование> ЗаказНаРазмещениеОснование { get; set; }
        public DbSet<ЗаказНаРазмещениеОтправитель> ЗаказНаРазмещениеОтправитель { get; set; }
        public DbSet<ЗаказНаРазмещениеПолучатель> ЗаказНаРазмещениеПолучатель { get; set; }
        public DbSet<ЗаказНаРазмещениеПредставитель> ЗаказНаРазмещениеПредставитель { get; set; }
        public DbSet<ЗаказНаРазмещениеСтрТабл> ЗаказНаРазмещениеСтрТабл { get; set; }
        public DbSet<ЗаказНаРазмещениеТаблДок> ЗаказНаРазмещениеТаблДок { get; set; }
        public DbSet<ЗаказНаРазмещениеФайл> ЗаказНаРазмещениеФайл { get; set; }
        public DbSet<Мх1Адрес> Мх1Адрес { get; set; }
        public DbSet<Мх1Документ> Мх1Документ { get; set; }
        public DbSet<Мх1ИтогТабл> Мх1ИтогТабл { get; set; }
        public DbSet<Мх1Основание> Мх1Основание { get; set; }
        public DbSet<Мх1Отправитель> Мх1Отправитель { get; set; }
        public DbSet<Мх1Получатель> Мх1Получатель { get; set; }
        public DbSet<Мх1Представитель> Мх1Представитель { get; set; }
        public DbSet<Мх1СтрТабл> Мх1СтрТабл { get; set; }
        public DbSet<Мх1ТаблДок> Мх1ТаблДок { get; set; }
        public DbSet<Мх1Файл> Мх1Файл { get; set; }
        public DbSet<АктПриемкиАдрИно> АктПриемкиАдрИно { get; set; }
        public DbSet<АктПриемкиАдрРФ> АктПриемкиАдрРФ { get; set; }
        public DbSet<АктПриемкиБанкРекв> АктПриемкиБанкРекв { get; set; }
        public DbSet<АктПриемкиВалюта> АктПриемкиВалюта { get; set; }
        public DbSet<АктПриемкиКонтакт> АктПриемкиКонтакт { get; set; }
        public DbSet<АктПриемкиНДС> АктПриемкиНДС { get; set; }
        public DbSet<АктПриемкиОснование> АктПриемкиОснование { get; set; }
        public DbSet<АктПриемкиПараметр> АктПриемкиПараметр { get; set; }
        public DbSet<АктПриемкиПодразделение> АктПриемкиПодразделение { get; set; }
        public DbSet<АктПриемкиСвФЛ> АктПриемкиСвФЛ { get; set; }
        public DbSet<АктПриемкиСвЮЛ> АктПриемкиСвЮЛ { get; set; }
        public DbSet<АктПриемкиХарактеристика> АктПриемкиХарактеристика { get; set; }
        public DbSet<ЗаказНаРазмещениеАдрИно> ЗаказНаРазмещениеАдрИно { get; set; }
        public DbSet<ЗаказНаРазмещениеАдрРФ> ЗаказНаРазмещениеАдрРФ { get; set; }
        public DbSet<ЗаказНаРазмещениеБанкРекв> ЗаказНаРазмещениеБанкРекв { get; set; }
        public DbSet<ЗаказНаРазмещениеКонтакт> ЗаказНаРазмещениеКонтакт { get; set; }
        public DbSet<ЗаказНаРазмещениеНДС> ЗаказНаРазмещениеНДС { get; set; }
        public DbSet<ЗаказНаРазмещениеПараметр> ЗаказНаРазмещениеПараметр { get; set; }
        public DbSet<ЗаказНаРазмещениеПодразделение> ЗаказНаРазмещениеПодразделение { get; set; }
        public DbSet<ЗаказНаРазмещениеРазмерКоробки> ЗаказНаРазмещениеРазмерКоробки { get; set; }
        public DbSet<ЗаказНаРазмещениеРазмерМалСтандарт> ЗаказНаРазмещениеРазмерМалСтандарт { get; set; }
        public DbSet<ЗаказНаРазмещениеРазмерУпаковки> ЗаказНаРазмещениеРазмерУпаковки { get; set; }
        public DbSet<ЗаказНаРазмещениеСвФЛ> ЗаказНаРазмещениеСвФЛ { get; set; }
        public DbSet<ЗаказНаРазмещениеСвЮЛ> ЗаказНаРазмещениеСвЮЛ { get; set; }
        public DbSet<ЗаказНаРазмещениеХарактеристика> ЗаказНаРазмещениеХарактеристика { get; set; }
        public DbSet<Мх1АдрИно> Мх1АдрИно { get; set; }
        public DbSet<Мх1АдрРФ> Мх1АдрРФ { get; set; }
        public DbSet<Мх1БанкРекв> Мх1БанкРекв { get; set; }
        public DbSet<Мх1Контакт> Мх1Контакт { get; set; }
        public DbSet<Мх1НДС> Мх1НДС { get; set; }
        public DbSet<Мх1Параметр> Мх1Параметр { get; set; }
        public DbSet<Мх1Подразделение> Мх1Подразделение { get; set; }
        public DbSet<Мх1СвФЛ> Мх1СвФЛ { get; set; }
        public DbSet<Мх1СвЮЛ> Мх1СвЮЛ { get; set; }
        public DbSet<Мх1Характеристика> Мх1Характеристика { get; set; }
        public DbSet<Клиенты> Клиенты { get; set; }
        public DbSet<Товар> Товар { get; set; }
        public DbSet<КодАВЕ> КодАВЕ { get; set; }
        public DbSet<КодНалСт> КодНалСт { get; set; }
        public DbSet<Мх3Адрес> Мх3Адрес { get; set; }
        public DbSet<Мх3АдрИно> Мх3АдрИно { get; set; }
        public DbSet<Мх3АдрРФ> Мх3АдрРФ { get; set; }
        public DbSet<Мх3БанкРекв> Мх3БанкРекв { get; set; }
        public DbSet<Мх3Документ> Мх3Документ { get; set; }
        public DbSet<Мх3ИтогТабл> Мх3ИтогТабл { get; set; }
        public DbSet<Мх3Контакт> Мх3Контакт { get; set; }
        public DbSet<Мх3Налог> Мх3Налог { get; set; }
        public DbSet<Мх3Основание> Мх3Основание { get; set; }
        public DbSet<Мх3Параметр> Мх3Параметр { get; set; }
        public DbSet<Мх3Представитель> Мх3Представитель { get; set; }
        public DbSet<Мх3СвФЛ> Мх3СвФЛ { get; set; }
        public DbSet<Мх3СвЮЛ> Мх3СвЮЛ { get; set; }
        public DbSet<Мх3СтрТабл> Мх3СтрТабл { get; set; }
        public DbSet<Мх3Участник> Мх3Участник { get; set; }
        public DbSet<Мх3Файл> Мх3Файл { get; set; }
        public DbSet<ЗаказНаОтгрузкуАдрес> ЗаказНаОтгрузкуАдрес { get; set; }
        public DbSet<ЗаказНаОтгрузкуАдрИно> ЗаказНаОтгрузкуАдрИно { get; set; }
        public DbSet<ЗаказНаОтгрузкуАдрРФ> ЗаказНаОтгрузкуАдрРФ { get; set; }
        public DbSet<ЗаказНаОтгрузкуБанкРекв> ЗаказНаОтгрузкуБанкРекв { get; set; }
        public DbSet<ЗаказНаОтгрузкуДокумент> ЗаказНаОтгрузкуДокумент { get; set; }
        public DbSet<ЗаказНаОтгрузкуИтогТабл> ЗаказНаОтгрузкуИтогТабл { get; set; }
        public DbSet<ЗаказНаОтгрузкуКонтакт> ЗаказНаОтгрузкуКонтакт { get; set; }
        public DbSet<ЗаказНаОтгрузкуНалог> ЗаказНаОтгрузкуНалог { get; set; }
        public DbSet<ЗаказНаОтгрузкуОснование> ЗаказНаОтгрузкуОснование { get; set; }
        public DbSet<ЗаказНаОтгрузкуПараметр> ЗаказНаОтгрузкуПараметр { get; set; }
        public DbSet<ЗаказНаОтгрузкуПредставитель> ЗаказНаОтгрузкуПредставитель { get; set; }
        public DbSet<ЗаказНаОтгрузкуСвФЛ> ЗаказНаОтгрузкуСвФЛ { get; set; }
        public DbSet<ЗаказНаОтгрузкуСвЮЛ> ЗаказНаОтгрузкуСвЮЛ { get; set; }
        public DbSet<ЗаказНаОтгрузкуСтрТабл> ЗаказНаОтгрузкуСтрТабл { get; set; }
        public DbSet<ЗаказНаОтгрузкуУчастник> ЗаказНаОтгрузкуУчастник { get; set; }
        public DbSet<ЗаказНаОтгрузкуФайл> ЗаказНаОтгрузкуФайл { get; set; }
        public DbSet<ДоставкаАдрес> ДоставкаАдрес { get; set; }
        public DbSet<ДоставкаДокумент> ДоставкаДокумент { get; set; }
        public DbSet<ДоставкаКонтакт> ДоставкаКонтакт { get; set; }
        public DbSet<ДоставкаОтправитель> ДоставкаОтправитель { get; set; }
        public DbSet<ДоставкаПолучатель> ДоставкаПолучатель { get; set; }
        public DbSet<ДоставкаСвФЛ> ДоставкаСвФЛ { get; set; }
        public DbSet<ДоставкаСвЮЛ> ДоставкаСвЮЛ { get; set; }
        public DbSet<ДоставкаСтрТабл> ДоставкаСтрТабл { get; set; }
        public DbSet<ДоставкаТаблДок> ДоставкаТаблДок { get; set; }
        public DbSet<ДоставкаФайл> ДоставкаФайл { get; set; }
        public DbSet<ДоставкаПараметр> ДоставкаПараметр { get; set; }
        public DbSet<WfStates> WfStates { get; set; }
        public DbSet<ЗаданиеНаДоставку> ЗаданиеНаДоставку { get; set; }
        public DbSet<Маршрут> Маршрут { get; set; }
        public DbSet<Перевозчик> Перевозчик { get; set; }
        public DbSet<ТТН> ТТН { get; set; }
        public DbSet<ТТНСопрДок> ТТНСопрДок { get; set; }
        public DbSet<ЗаказНаОтгрузкуТаблДок> ЗаказНаОтгрузкуТаблДок { get; set; }
        public DbSet<Мх3ТаблДок> Мх3ТаблДок { get; set; }
        public DbSet<НормАдр> НормАдр { get; set; }
    }
}
