//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderNote
    {
        public int OrderNoteID { get; set; }
        public int OrderID { get; set; }
        public string Note { get; set; }
        public string UserID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
