//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDocRow = new HashSet<OrderDocRow>();
            this.OrderFactRow = new HashSet<OrderFactRow>();
            this.OrderNote = new HashSet<OrderNote>();
        }
    
        public int OrderID { get; set; }
        public string WmsOrderId { get; set; }
        public string WmsOrderTy { get; set; }
        public System.DateTime DT { get; set; }
        public Nullable<int> ShipID { get; set; }
        public string UserID { get; set; }
        public Nullable<byte> OrderTypeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> DestID { get; set; }
        public string CustOrderID { get; set; }
        public Nullable<System.DateTime> CustOrderDT { get; set; }
        public int WfState { get; set; }
        public Nullable<int> SupplID { get; set; }
        public short WmsOrderVer { get; set; }
        public Nullable<int> C_WmsOrderId { get; set; }
        public Nullable<System.DateTime> WmsCloseDT { get; set; }
        public Nullable<bool> IsDocEqToFact { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Dest Dest { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual Ship Ship { get; set; }
        public virtual ICollection<OrderDocRow> OrderDocRow { get; set; }
        public virtual ICollection<OrderFactRow> OrderFactRow { get; set; }
        public virtual ICollection<OrderNote> OrderNote { get; set; }
        public virtual Customer Supplier { get; set; }
    }
}
