//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDocRow
    {
        public int OrderDocRowID { get; set; }
        public int OrderID { get; set; }
        public int PartID { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> ExpireDT { get; set; }
        public string InvQual { get; set; }
        public string SpecInvID { get; set; }
        public int Qty { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> RowNo { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Partm Partm { get; set; }
    }
}
