//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderType
    {
        public OrderType()
        {
            this.Order = new HashSet<Order>();
        }
    
        public byte OrderTypeID { get; set; }
        public string Name { get; set; }
        public string WmsOrderTy { get; set; }
        public Nullable<int> WmsOrderLastID { get; set; }
        public string WmsOrderRowTy { get; set; }
        public string WmsOrderPrefix { get; set; }
        public Nullable<decimal> WmsOrderFinalTransTy { get; set; }
        public Nullable<decimal> WmsOrderRowFinalTransTy { get; set; }
        public string Sign { get; set; }
        public Nullable<byte> ExportDocID { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ExportDoc ExportDoc { get; set; }
    }
}
