//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partm
    {
        public Partm()
        {
            this.OrderDocRow = new HashSet<OrderDocRow>();
            this.OrderFactRow = new HashSet<OrderFactRow>();
        }
    
        public string eanid { get; set; }
        public string partdsc { get; set; }
        public string partdsc2 { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> buwg { get; set; }
        public Nullable<decimal> widthppu { get; set; }
        public Nullable<decimal> lengthppu { get; set; }
        public Nullable<decimal> heightppu { get; set; }
        public Nullable<decimal> ppuwg { get; set; }
        public Nullable<int> qpkg2 { get; set; }
        public Nullable<decimal> widthspu { get; set; }
        public Nullable<decimal> lengthspu { get; set; }
        public Nullable<decimal> heightspu { get; set; }
        public Nullable<decimal> spuwg { get; set; }
        public Nullable<int> qpkg1 { get; set; }
        public bool specaccount { get; set; }
        public bool glass { get; set; }
        public string hazcl { get; set; }
        public string tempcl { get; set; }
        public int minorder { get; set; }
        public int mulorder { get; set; }
        public string id1 { get; set; }
        public Nullable<int> id2 { get; set; }
        public int PartID { get; set; }
    
        public virtual ICollection<OrderDocRow> OrderDocRow { get; set; }
        public virtual ICollection<OrderFactRow> OrderFactRow { get; set; }
    }
}
