//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        public Ship()
        {
            this.Order = new HashSet<Order>();
            this.ShipCont = new HashSet<ShipCont>();
        }
    
        public int ShipID { get; set; }
        public string WmsShipID { get; set; }
        public Nullable<int> LadingID { get; set; }
    
        public virtual Lading Lading { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<ShipCont> ShipCont { get; set; }
    }
}
