//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipCont
    {
        public int ShipContID { get; set; }
        public int ShipID { get; set; }
        public string No { get; set; }
        public Nullable<decimal> Wg { get; set; }
        public Nullable<decimal> Vol { get; set; }
        public string CoTy { get; set; }
    
        public virtual Ship Ship { get; set; }
        public virtual CoTy CoTy1 { get; set; }
    }
}
