//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктПриемкиАдрРФ
    {
        public string Индекс { get; set; }
        public string КодРегион { get; set; }
        public string Район { get; set; }
        public string Город { get; set; }
        public string НаселПункт { get; set; }
        public string Улица { get; set; }
        public string Дом { get; set; }
        public string Корпус { get; set; }
        public string Кварт { get; set; }
        public Nullable<int> Адрес_Id { get; set; }
        public int АдрРФ_Id { get; set; }
    
        public virtual АктПриемкиАдрес АктПриемкиАдрес { get; set; }
    }
}
