//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктПриемкиКонтакт
    {
        public string Факс { get; set; }
        public string Телефон { get; set; }
        public string МобТелефон { get; set; }
        public string Internet { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> Покупатель_Id { get; set; }
        public Nullable<int> Грузоотправитель_Id { get; set; }
        public Nullable<int> Грузополучатель_Id { get; set; }
        public Nullable<int> Поставщик_Id { get; set; }
        public int Контакт_Id { get; set; }
    
        public virtual АктПриемкиГрузоотправитель АктПриемкиГрузоотправитель { get; set; }
        public virtual АктПриемкиГрузополучатель АктПриемкиГрузополучатель { get; set; }
        public virtual АктПриемкиПокупатель АктПриемкиПокупатель { get; set; }
        public virtual АктПриемкиПоставщик АктПриемкиПоставщик { get; set; }
    }
}
