//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктПриемкиСтрОтклонения
    {
        public АктПриемкиСтрОтклонения()
        {
            this.АктПриемкиПоДокументам = new HashSet<АктПриемкиПоДокументам>();
            this.АктПриемкиПоФакту = new HashSet<АктПриемкиПоФакту>();
            this.АктПриемкиСписокПараметр = new HashSet<АктПриемкиСписокПараметр>();
            this.АктПриемкиСписокХарактеристика = new HashSet<АктПриемкиСписокХарактеристика>();
            this.АктПриемкиНДС = new HashSet<АктПриемкиНДС>();
        }
    
        public string ПорНомер { get; set; }
        public string Название { get; set; }
        public Nullable<int> Кол_во { get; set; }
        public string ЕдИзм { get; set; }
        public Nullable<decimal> СуммаБезНал { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public string Примечание { get; set; }
        public string ОКЕИ { get; set; }
        public string Артикул { get; set; }
        public string Описание { get; set; }
        public string Идентификатор { get; set; }
        public string КодПокупателя { get; set; }
        public string КодПоставщика { get; set; }
        public string GTIN { get; set; }
        public int СтрОтклонения_Id { get; set; }
        public Nullable<int> СписокСтрОтклонения_Id { get; set; }
    
        public virtual ICollection<АктПриемкиПоДокументам> АктПриемкиПоДокументам { get; set; }
        public virtual ICollection<АктПриемкиПоФакту> АктПриемкиПоФакту { get; set; }
        public virtual ICollection<АктПриемкиСписокПараметр> АктПриемкиСписокПараметр { get; set; }
        public virtual АктПриемкиСписокСтрОтклонения АктПриемкиСписокСтрОтклонения { get; set; }
        public virtual ICollection<АктПриемкиСписокХарактеристика> АктПриемкиСписокХарактеристика { get; set; }
        public virtual ICollection<АктПриемкиНДС> АктПриемкиНДС { get; set; }
    }
}
