//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктПриемкиСвФЛ
    {
        public string ИНН { get; set; }
        public string ДатаРождения { get; set; }
        public string Должность { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Фамилия { get; set; }
        public string Пол { get; set; }
        public string Обращение { get; set; }
        public string Название { get; set; }
        public string ОКФС { get; set; }
        public string ОКОПФ { get; set; }
        public string ОКПО { get; set; }
        public string ОКДП { get; set; }
        public string ОКВЭД { get; set; }
        public Nullable<int> Покупатель_Id { get; set; }
        public Nullable<int> Грузоотправитель_Id { get; set; }
        public Nullable<int> Грузополучатель_Id { get; set; }
        public Nullable<int> Поставщик_Id { get; set; }
        public int СвФЛ_Id { get; set; }
    
        public virtual АктПриемкиГрузоотправитель АктПриемкиГрузоотправитель { get; set; }
        public virtual АктПриемкиГрузополучатель АктПриемкиГрузополучатель { get; set; }
        public virtual АктПриемкиПокупатель АктПриемкиПокупатель { get; set; }
        public virtual АктПриемкиПоставщик АктПриемкиПоставщик { get; set; }
    }
}
