//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктПриемкиАдрес
    {
        public АктПриемкиАдрес()
        {
            this.АктПриемкиАдрИно = new HashSet<АктПриемкиАдрИно>();
            this.АктПриемкиАдрРФ = new HashSet<АктПриемкиАдрРФ>();
        }
    
        public string Тип { get; set; }
        public string АдрТекст { get; set; }
        public int Адрес_Id { get; set; }
        public Nullable<int> СписокАдрес_Id { get; set; }
    
        public virtual АктПриемкиСписокАдрес АктПриемкиСписокАдрес { get; set; }
        public virtual ICollection<АктПриемкиАдрИно> АктПриемкиАдрИно { get; set; }
        public virtual ICollection<АктПриемкиАдрРФ> АктПриемкиАдрРФ { get; set; }
    }
}
