//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктПриемкиОснование
    {
        public string Номер { get; set; }
        public string Дата { get; set; }
        public string Название { get; set; }
        public Nullable<int> Бухгалтер_Id { get; set; }
        public Nullable<int> Руководитель_Id { get; set; }
        public Nullable<int> СписокОснование_Id { get; set; }
        public int Основание_Id { get; set; }
    
        public virtual АктПриемкиБухгалтер АктПриемкиБухгалтер { get; set; }
        public virtual АктПриемкиРуководитель АктПриемкиРуководитель { get; set; }
        public virtual АктПриемкиСписокОснование АктПриемкиСписокОснование { get; set; }
    }
}
