//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктПриемкиСписокХарактеристика
    {
        public АктПриемкиСписокХарактеристика()
        {
            this.АктПриемкиХарактеристика = new HashSet<АктПриемкиХарактеристика>();
        }
    
        public int СписокХарактеристика_Id { get; set; }
        public Nullable<int> СтрОтклонения_Id { get; set; }
    
        public virtual АктПриемкиСтрОтклонения АктПриемкиСтрОтклонения { get; set; }
        public virtual ICollection<АктПриемкиХарактеристика> АктПриемкиХарактеристика { get; set; }
    }
}
