//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктПриемкиДокумент
    {
        public АктПриемкиДокумент()
        {
            this.АктПриемкиСписокОснование = new HashSet<АктПриемкиСписокОснование>();
            this.АктПриемкиСписокПараметр = new HashSet<АктПриемкиСписокПараметр>();
            this.АктПриемкиСписокСтрОтклонения = new HashSet<АктПриемкиСписокСтрОтклонения>();
            this.АктПриемкиСтороны = new HashSet<АктПриемкиСтороны>();
            this.АктПриемкиВалюта = new HashSet<АктПриемкиВалюта>();
        }
    
        public string Номер { get; set; }
        public string Дата { get; set; }
        public string Время { get; set; }
        public string Название { get; set; }
        public string Примечание { get; set; }
        public int Документ_Id { get; set; }
        public Nullable<int> Файл_Id { get; set; }
    
        public virtual ICollection<АктПриемкиСписокОснование> АктПриемкиСписокОснование { get; set; }
        public virtual ICollection<АктПриемкиСписокПараметр> АктПриемкиСписокПараметр { get; set; }
        public virtual ICollection<АктПриемкиСписокСтрОтклонения> АктПриемкиСписокСтрОтклонения { get; set; }
        public virtual ICollection<АктПриемкиСтороны> АктПриемкиСтороны { get; set; }
        public virtual АктПриемкиФайл АктПриемкиФайл { get; set; }
        public virtual ICollection<АктПриемкиВалюта> АктПриемкиВалюта { get; set; }
    }
}
