//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктПриемкиНДС
    {
        public string Название { get; set; }
        public string Ставка { get; set; }
        public string ТипСтавки { get; set; }
        public string Сумма { get; set; }
        public Nullable<int> ПоДокументам_Id { get; set; }
        public Nullable<int> ПоФакту_Id { get; set; }
        public Nullable<int> СтрОтклонения_Id { get; set; }
        public int НДС_Id { get; set; }
    
        public virtual АктПриемкиПоДокументам АктПриемкиПоДокументам { get; set; }
        public virtual АктПриемкиПоФакту АктПриемкиПоФакту { get; set; }
        public virtual АктПриемкиСтрОтклонения АктПриемкиСтрОтклонения { get; set; }
    }
}
