//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктПриемкиПоДокументам
    {
        public АктПриемкиПоДокументам()
        {
            this.АктПриемкиНДС = new HashSet<АктПриемкиНДС>();
        }
    
        public Nullable<int> Кол_во { get; set; }
        public Nullable<decimal> СуммаБезНал { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public int ПоДокументам_Id { get; set; }
        public Nullable<int> СтрОтклонения_Id { get; set; }
    
        public virtual АктПриемкиСтрОтклонения АктПриемкиСтрОтклонения { get; set; }
        public virtual ICollection<АктПриемкиНДС> АктПриемкиНДС { get; set; }
    }
}
