//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктПриемкиРуководитель
    {
        public АктПриемкиРуководитель()
        {
            this.АктПриемкиОснование = new HashSet<АктПриемкиОснование>();
        }
    
        public string ФИО { get; set; }
        public string Должность { get; set; }
        public int Руководитель_Id { get; set; }
        public Nullable<int> Представители_Id { get; set; }
    
        public virtual АктПриемкиПредставители АктПриемкиПредставители { get; set; }
        public virtual ICollection<АктПриемкиОснование> АктПриемкиОснование { get; set; }
    }
}
