//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктПриемкиГрузополучатель
    {
        public АктПриемкиГрузополучатель()
        {
            this.АктПриемкиПредставители = new HashSet<АктПриемкиПредставители>();
            this.АктПриемкиСписокАдрес = new HashSet<АктПриемкиСписокАдрес>();
            this.АктПриемкиСписокПараметр = new HashSet<АктПриемкиСписокПараметр>();
            this.АктПриемкиБанкРекв = new HashSet<АктПриемкиБанкРекв>();
            this.АктПриемкиКонтакт = new HashSet<АктПриемкиКонтакт>();
            this.АктПриемкиПодразделение = new HashSet<АктПриемкиПодразделение>();
            this.АктПриемкиСвФЛ = new HashSet<АктПриемкиСвФЛ>();
            this.АктПриемкиСвЮЛ = new HashSet<АктПриемкиСвЮЛ>();
        }
    
        public string Примечание { get; set; }
        public string Название { get; set; }
        public string GLN { get; set; }
        public int Грузополучатель_Id { get; set; }
        public Nullable<int> Стороны_Id { get; set; }
    
        public virtual ICollection<АктПриемкиПредставители> АктПриемкиПредставители { get; set; }
        public virtual ICollection<АктПриемкиСписокАдрес> АктПриемкиСписокАдрес { get; set; }
        public virtual ICollection<АктПриемкиСписокПараметр> АктПриемкиСписокПараметр { get; set; }
        public virtual АктПриемкиСтороны АктПриемкиСтороны { get; set; }
        public virtual ICollection<АктПриемкиБанкРекв> АктПриемкиБанкРекв { get; set; }
        public virtual ICollection<АктПриемкиКонтакт> АктПриемкиКонтакт { get; set; }
        public virtual ICollection<АктПриемкиПодразделение> АктПриемкиПодразделение { get; set; }
        public virtual ICollection<АктПриемкиСвФЛ> АктПриемкиСвФЛ { get; set; }
        public virtual ICollection<АктПриемкиСвЮЛ> АктПриемкиСвЮЛ { get; set; }
    }
}
