//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДоставкаТаблДок
    {
        public ДоставкаТаблДок()
        {
            this.ДоставкаСтрТабл = new HashSet<ДоставкаСтрТабл>();
        }
    
        public string Название { get; set; }
        public string Тип { get; set; }
        public Nullable<int> Документ_Id { get; set; }
        public int ТаблДок_Id { get; set; }
    
        public virtual ДоставкаДокумент ДоставкаДокумент { get; set; }
        public virtual ICollection<ДоставкаСтрТабл> ДоставкаСтрТабл { get; set; }
    }
}
