//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДоставкаДокумент
    {
        public ДоставкаДокумент()
        {
            this.ДоставкаОтправитель = new HashSet<ДоставкаОтправитель>();
            this.ДоставкаПолучатель = new HashSet<ДоставкаПолучатель>();
            this.ДоставкаТаблДок = new HashSet<ДоставкаТаблДок>();
            this.ДоставкаПараметр = new HashSet<ДоставкаПараметр>();
        }
    
        public Nullable<System.DateTime> Дата { get; set; }
        public string Номер { get; set; }
        public Nullable<int> Файл_Id { get; set; }
        public int Документ_Id { get; set; }
    
        public virtual ДоставкаФайл ДоставкаФайл { get; set; }
        public virtual ICollection<ДоставкаОтправитель> ДоставкаОтправитель { get; set; }
        public virtual ICollection<ДоставкаПолучатель> ДоставкаПолучатель { get; set; }
        public virtual ICollection<ДоставкаТаблДок> ДоставкаТаблДок { get; set; }
        public virtual ICollection<ДоставкаПараметр> ДоставкаПараметр { get; set; }
    }
}
