//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДоставкаАдрес
    {
        public string Тип { get; set; }
        public string Наим { get; set; }
        public string АдрТекст { get; set; }
        public Nullable<int> Отправитель_Id { get; set; }
        public Nullable<int> Получатель_Id { get; set; }
        public int Адрес_Id { get; set; }
        public string Маршрут_Id { get; set; }
        public Nullable<int> НормАдр_Id { get; set; }
    
        public virtual ДоставкаОтправитель ДоставкаОтправитель { get; set; }
        public virtual ДоставкаПолучатель ДоставкаПолучатель { get; set; }
        public virtual НормАдр НормАдр { get; set; }
    }
}
