//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаОтгрузкуПредставитель
    {
        public ЗаказНаОтгрузкуПредставитель()
        {
            this.ЗаказНаОтгрузкуСвФЛ = new HashSet<ЗаказНаОтгрузкуСвФЛ>();
        }
    
        public string Должность { get; set; }
        public string Роль { get; set; }
        public int Представитель_Id { get; set; }
        public Nullable<int> Участник_Id { get; set; }
    
        public virtual ICollection<ЗаказНаОтгрузкуСвФЛ> ЗаказНаОтгрузкуСвФЛ { get; set; }
        public virtual ЗаказНаОтгрузкуУчастник ЗаказНаОтгрузкуУчастник { get; set; }
    }
}
