//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаОтгрузкуПараметр
    {
        public string Имя { get; set; }
        public string Значение { get; set; }
        public Nullable<int> Участник_Id { get; set; }
        public Nullable<int> Основание_Id { get; set; }
        public Nullable<int> СтрТабл_Id { get; set; }
        public Nullable<int> ИтогТабл_Id { get; set; }
        public Nullable<int> Документ_Id { get; set; }
        public long Параметр_Id { get; set; }
    
        public virtual ЗаказНаОтгрузкуДокумент ЗаказНаОтгрузкуДокумент { get; set; }
        public virtual ЗаказНаОтгрузкуИтогТабл ЗаказНаОтгрузкуИтогТабл { get; set; }
        public virtual ЗаказНаОтгрузкуОснование ЗаказНаОтгрузкуОснование { get; set; }
        public virtual ЗаказНаОтгрузкуСтрТабл ЗаказНаОтгрузкуСтрТабл { get; set; }
        public virtual ЗаказНаОтгрузкуУчастник ЗаказНаОтгрузкуУчастник { get; set; }
    }
}
