//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаОтгрузкуДокумент
    {
        public ЗаказНаОтгрузкуДокумент()
        {
            this.ЗаказНаОтгрузкуОснование = new HashSet<ЗаказНаОтгрузкуОснование>();
            this.ЗаказНаОтгрузкуПараметр = new HashSet<ЗаказНаОтгрузкуПараметр>();
            this.ЗаказНаОтгрузкуУчастник = new HashSet<ЗаказНаОтгрузкуУчастник>();
            this.ЗаказНаОтгрузкуТаблДок = new HashSet<ЗаказНаОтгрузкуТаблДок>();
        }
    
        public string Дата { get; set; }
        public string Номер { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public string Примечание { get; set; }
        public int Документ_Id { get; set; }
        public Nullable<int> Файл_Id { get; set; }
        public string C_WmsOrderId { get; set; }
        public string C_WmsOrderTy { get; set; }
        public Nullable<System.DateTime> C_WmsOrderDt { get; set; }
    
        public virtual ICollection<ЗаказНаОтгрузкуОснование> ЗаказНаОтгрузкуОснование { get; set; }
        public virtual ICollection<ЗаказНаОтгрузкуПараметр> ЗаказНаОтгрузкуПараметр { get; set; }
        public virtual ICollection<ЗаказНаОтгрузкуУчастник> ЗаказНаОтгрузкуУчастник { get; set; }
        public virtual ЗаказНаОтгрузкуФайл ЗаказНаОтгрузкуФайл { get; set; }
        public virtual ICollection<ЗаказНаОтгрузкуТаблДок> ЗаказНаОтгрузкуТаблДок { get; set; }
    }
}
