//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаОтгрузкуТаблДок
    {
        public ЗаказНаОтгрузкуТаблДок()
        {
            this.ЗаказНаОтгрузкуИтогТабл = new HashSet<ЗаказНаОтгрузкуИтогТабл>();
            this.ЗаказНаОтгрузкуСтрТабл = new HashSet<ЗаказНаОтгрузкуСтрТабл>();
        }
    
        public string Тип { get; set; }
        public string Наим { get; set; }
        public int Таблица_Id { get; set; }
        public Nullable<int> Документ_Id { get; set; }
    
        public virtual ЗаказНаОтгрузкуДокумент ЗаказНаОтгрузкуДокумент { get; set; }
        public virtual ICollection<ЗаказНаОтгрузкуИтогТабл> ЗаказНаОтгрузкуИтогТабл { get; set; }
        public virtual ICollection<ЗаказНаОтгрузкуСтрТабл> ЗаказНаОтгрузкуСтрТабл { get; set; }
    }
}
