//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаРазмещениеРазмерКоробки
    {
        public Nullable<long> Кол_воУп { get; set; }
        public Nullable<long> Ширина { get; set; }
        public Nullable<long> Длина { get; set; }
        public Nullable<long> Высота { get; set; }
        public Nullable<long> Вес { get; set; }
        public Nullable<long> Объем { get; set; }
        public Nullable<int> СтрТабл_Id { get; set; }
        public int РазмерКоробки_Id { get; set; }
    
        public virtual ЗаказНаРазмещениеСтрТабл ЗаказНаРазмещениеСтрТабл { get; set; }
    }
}
