//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаРазмещениеФайл
    {
        public ЗаказНаРазмещениеФайл()
        {
            this.ЗаказНаРазмещениеДокумент = new HashSet<ЗаказНаРазмещениеДокумент>();
        }
    
        public string ВерсПрог { get; set; }
        public string ВерсияФормата { get; set; }
        public string Имя { get; set; }
        public string Формат { get; set; }
        public string КодФормы { get; set; }
        public int Файл_Id { get; set; }
        public System.DateTime C_CreatedDT { get; set; }
        public bool C_Processed { get; set; }
        public Nullable<System.DateTime> C_ProcessedDT { get; set; }
    
        public virtual ICollection<ЗаказНаРазмещениеДокумент> ЗаказНаРазмещениеДокумент { get; set; }
    }
}
