//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаРазмещениеПолучатель
    {
        public ЗаказНаРазмещениеПолучатель()
        {
            this.ЗаказНаРазмещениеАдрес = new HashSet<ЗаказНаРазмещениеАдрес>();
            this.ЗаказНаРазмещениеБанкРекв = new HashSet<ЗаказНаРазмещениеБанкРекв>();
            this.ЗаказНаРазмещениеКонтакт = new HashSet<ЗаказНаРазмещениеКонтакт>();
            this.ЗаказНаРазмещениеПараметр = new HashSet<ЗаказНаРазмещениеПараметр>();
            this.ЗаказНаРазмещениеПодразделение = new HashSet<ЗаказНаРазмещениеПодразделение>();
            this.ЗаказНаРазмещениеСвФЛ = new HashSet<ЗаказНаРазмещениеСвФЛ>();
            this.ЗаказНаРазмещениеСвЮЛ = new HashSet<ЗаказНаРазмещениеСвЮЛ>();
        }
    
        public string Название { get; set; }
        public int Получатель_Id { get; set; }
        public Nullable<int> Документ_Id { get; set; }
    
        public virtual ICollection<ЗаказНаРазмещениеАдрес> ЗаказНаРазмещениеАдрес { get; set; }
        public virtual ЗаказНаРазмещениеДокумент ЗаказНаРазмещениеДокумент { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеБанкРекв> ЗаказНаРазмещениеБанкРекв { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеКонтакт> ЗаказНаРазмещениеКонтакт { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеПараметр> ЗаказНаРазмещениеПараметр { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеПодразделение> ЗаказНаРазмещениеПодразделение { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеСвФЛ> ЗаказНаРазмещениеСвФЛ { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеСвЮЛ> ЗаказНаРазмещениеСвЮЛ { get; set; }
    }
}
