//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаОтгрузкуКонтакт
    {
        public string Телефон { get; set; }
        public string Факс { get; set; }
        public string Email { get; set; }
        public string Internet { get; set; }
        public Nullable<int> Участник_Id { get; set; }
        public int Контакт_Id { get; set; }
    
        public virtual ЗаказНаОтгрузкуУчастник ЗаказНаОтгрузкуУчастник { get; set; }
    }
}
