//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаОтгрузкуАдрИно
    {
        public string КодСтр { get; set; }
        public string АдрТекст { get; set; }
        public Nullable<int> Адрес_Id { get; set; }
        public int АдрИно_Id { get; set; }
    
        public virtual ЗаказНаОтгрузкуАдрес ЗаказНаОтгрузкуАдрес { get; set; }
    }
}
