//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаРазмещениеОснование
    {
        public ЗаказНаРазмещениеОснование()
        {
            this.ЗаказНаРазмещениеПараметр = new HashSet<ЗаказНаРазмещениеПараметр>();
        }
    
        public string Номер { get; set; }
        public string Дата { get; set; }
        public string Наим { get; set; }
        public Nullable<float> СуммаБезНал { get; set; }
        public Nullable<float> Сумма { get; set; }
        public string Срок { get; set; }
        public int Основание_Id { get; set; }
        public Nullable<int> Документ_Id { get; set; }
    
        public virtual ЗаказНаРазмещениеДокумент ЗаказНаРазмещениеДокумент { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеПараметр> ЗаказНаРазмещениеПараметр { get; set; }
    }
}
