//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаОтгрузкуНалог
    {
        public string Наим { get; set; }
        public string Ставка { get; set; }
        public string ТипСтавки { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<int> СтрТабл_Id { get; set; }
        public Nullable<int> ИтогТабл_Id { get; set; }
        public int Налог_Id { get; set; }
    
        public virtual ЗаказНаОтгрузкуИтогТабл ЗаказНаОтгрузкуИтогТабл { get; set; }
        public virtual ЗаказНаОтгрузкуСтрТабл ЗаказНаОтгрузкуСтрТабл { get; set; }
    }
}
