//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаРазмещениеПараметр
    {
        public string Имя { get; set; }
        public string Значение { get; set; }
        public Nullable<int> Основание_Id { get; set; }
        public Nullable<int> Отправитель_Id { get; set; }
        public Nullable<int> Получатель_Id { get; set; }
        public Nullable<int> ИтогТабл_Id { get; set; }
        public Nullable<int> Документ_Id { get; set; }
        public int Параметр_Id { get; set; }
    
        public virtual ЗаказНаРазмещениеДокумент ЗаказНаРазмещениеДокумент { get; set; }
        public virtual ЗаказНаРазмещениеИтогТабл ЗаказНаРазмещениеИтогТабл { get; set; }
        public virtual ЗаказНаРазмещениеОснование ЗаказНаРазмещениеОснование { get; set; }
        public virtual ЗаказНаРазмещениеОтправитель ЗаказНаРазмещениеОтправитель { get; set; }
        public virtual ЗаказНаРазмещениеПолучатель ЗаказНаРазмещениеПолучатель { get; set; }
    }
}
