//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаРазмещениеСтрТабл
    {
        public ЗаказНаРазмещениеСтрТабл()
        {
            this.ЗаказНаРазмещениеНДС = new HashSet<ЗаказНаРазмещениеНДС>();
            this.ЗаказНаРазмещениеРазмерКоробки = new HashSet<ЗаказНаРазмещениеРазмерКоробки>();
            this.ЗаказНаРазмещениеРазмерМалСтандарт = new HashSet<ЗаказНаРазмещениеРазмерМалСтандарт>();
            this.ЗаказНаРазмещениеРазмерУпаковки = new HashSet<ЗаказНаРазмещениеРазмерУпаковки>();
            this.ЗаказНаРазмещениеХарактеристика = new HashSet<ЗаказНаРазмещениеХарактеристика>();
        }
    
        public string ПорНомер { get; set; }
        public string Название { get; set; }
        public Nullable<int> Кол_во { get; set; }
        public string ЕдИзм { get; set; }
        public string ОКЕИ { get; set; }
        public string Код { get; set; }
        public string Цена { get; set; }
        public Nullable<decimal> СуммаБезНал { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public string Примечание { get; set; }
        public string Описание { get; set; }
        public string Серия { get; set; }
        public Nullable<System.DateTime> СрокГодности { get; set; }
        public Nullable<System.DateTime> ДатаИзг { get; set; }
        public string ШтрихКод { get; set; }
        public string Качество { get; set; }
        public string ТемпРежим { get; set; }
        public string КлассОпасн { get; set; }
        public string Производитель { get; set; }
        public Nullable<bool> Стекло { get; set; }
        public Nullable<bool> Пку { get; set; }
        public string ОригПорНомер { get; set; }
        public Nullable<long> МинЗаказ { get; set; }
        public Nullable<long> КратнЗаказ { get; set; }
        public int СтрТабл_Id { get; set; }
        public Nullable<int> ТаблДок_Id { get; set; }
        public string Маркер { get; set; }
    
        public virtual ЗаказНаРазмещениеТаблДок ЗаказНаРазмещениеТаблДок { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеНДС> ЗаказНаРазмещениеНДС { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеРазмерКоробки> ЗаказНаРазмещениеРазмерКоробки { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеРазмерМалСтандарт> ЗаказНаРазмещениеРазмерМалСтандарт { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеРазмерУпаковки> ЗаказНаРазмещениеРазмерУпаковки { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеХарактеристика> ЗаказНаРазмещениеХарактеристика { get; set; }
    }
}
