//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаданиеНаДоставку
    {
        public ЗаданиеНаДоставку()
        {
            this.ТТН = new HashSet<ТТН>();
        }
    
        public int ЗаданиеНаДоставку_Id { get; set; }
        public string Маршрут_Id { get; set; }
        public Nullable<int> Перевозчик_Id { get; set; }
        public string Номер { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Примечание { get; set; }
        public Nullable<decimal> Вес { get; set; }
        public Nullable<decimal> Объем { get; set; }
        public int C_WfState { get; set; }
        public System.DateTime C_WfLastUpdateDT { get; set; }
        public string C_WfLastUpdateUser { get; set; }
        public System.DateTime C_CreatedDT { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<int> Кол_воМест { get; set; }
        public string Ворота { get; set; }
        public Nullable<System.DateTime> ВремяЗагрузки { get; set; }
        public Nullable<System.DateTime> ВремяОтправки { get; set; }
        public short Приоритет { get; set; }
    
        public virtual Маршрут Маршрут { get; set; }
        public virtual Перевозчик Перевозчик { get; set; }
        public virtual ICollection<ТТН> ТТН { get; set; }
    }
}
