//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаОтгрузкуУчастник
    {
        public ЗаказНаОтгрузкуУчастник()
        {
            this.ЗаказНаОтгрузкуАдрес = new HashSet<ЗаказНаОтгрузкуАдрес>();
            this.ЗаказНаОтгрузкуБанкРекв = new HashSet<ЗаказНаОтгрузкуБанкРекв>();
            this.ЗаказНаОтгрузкуКонтакт = new HashSet<ЗаказНаОтгрузкуКонтакт>();
            this.ЗаказНаОтгрузкуПараметр = new HashSet<ЗаказНаОтгрузкуПараметр>();
            this.ЗаказНаОтгрузкуПредставитель = new HashSet<ЗаказНаОтгрузкуПредставитель>();
            this.ЗаказНаОтгрузкуСвФЛ = new HashSet<ЗаказНаОтгрузкуСвФЛ>();
            this.ЗаказНаОтгрузкуСвЮЛ = new HashSet<ЗаказНаОтгрузкуСвЮЛ>();
        }
    
        public string Роль { get; set; }
        public int Участник_Id { get; set; }
        public Nullable<int> Документ_Id { get; set; }
    
        public virtual ICollection<ЗаказНаОтгрузкуАдрес> ЗаказНаОтгрузкуАдрес { get; set; }
        public virtual ICollection<ЗаказНаОтгрузкуБанкРекв> ЗаказНаОтгрузкуБанкРекв { get; set; }
        public virtual ЗаказНаОтгрузкуДокумент ЗаказНаОтгрузкуДокумент { get; set; }
        public virtual ICollection<ЗаказНаОтгрузкуКонтакт> ЗаказНаОтгрузкуКонтакт { get; set; }
        public virtual ICollection<ЗаказНаОтгрузкуПараметр> ЗаказНаОтгрузкуПараметр { get; set; }
        public virtual ICollection<ЗаказНаОтгрузкуПредставитель> ЗаказНаОтгрузкуПредставитель { get; set; }
        public virtual ICollection<ЗаказНаОтгрузкуСвФЛ> ЗаказНаОтгрузкуСвФЛ { get; set; }
        public virtual ICollection<ЗаказНаОтгрузкуСвЮЛ> ЗаказНаОтгрузкуСвЮЛ { get; set; }
    }
}
