//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказНаРазмещениеИтогТабл
    {
        public ЗаказНаРазмещениеИтогТабл()
        {
            this.ЗаказНаРазмещениеНДС = new HashSet<ЗаказНаРазмещениеНДС>();
            this.ЗаказНаРазмещениеПараметр = new HashSet<ЗаказНаРазмещениеПараметр>();
            this.ЗаказНаРазмещениеХарактеристика = new HashSet<ЗаказНаРазмещениеХарактеристика>();
        }
    
        public string Тип { get; set; }
        public Nullable<float> Нетто { get; set; }
        public Nullable<float> СуммаБезНал { get; set; }
        public Nullable<float> Кол_во { get; set; }
        public Nullable<float> Сумма { get; set; }
        public int ИтогТабл_Id { get; set; }
        public Nullable<int> ТаблДок_Id { get; set; }
    
        public virtual ЗаказНаРазмещениеТаблДок ЗаказНаРазмещениеТаблДок { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеНДС> ЗаказНаРазмещениеНДС { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеПараметр> ЗаказНаРазмещениеПараметр { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеХарактеристика> ЗаказНаРазмещениеХарактеристика { get; set; }
    }
}
