//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public int Код { get; set; }
        public string Название { get; set; }
        public string ЮрАдрес { get; set; }
        public string Адрес { get; set; }
        public string Телефон { get; set; }
        public string Факс { get; set; }
        public string Email { get; set; }
        public string WWW { get; set; }
        public string Банк { get; set; }
        public string БИК { get; set; }
        public string КСчет { get; set; }
        public string РСчет { get; set; }
        public string ИдПодразделения { get; set; }
        public string Подразделение { get; set; }
        public string ИНН { get; set; }
        public string КПП { get; set; }
        public string ОКДП { get; set; }
        public string ОКПО { get; set; }
        public bool Активный { get; set; }
        public string Примечание { get; set; }
        public string ПрефиксМХ1 { get; set; }
        public string ПрефиксАктПриемки { get; set; }
        public string ПрефиксМХ3 { get; set; }
    }
}
