//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Маршрут
    {
        public Маршрут()
        {
            this.ЗаданиеНаДоставку = new HashSet<ЗаданиеНаДоставку>();
            this.НормАдр = new HashSet<НормАдр>();
        }
    
        public string Маршрут_Id { get; set; }
        public string Примечание { get; set; }
        public string Ворота { get; set; }
        public Nullable<System.DateTime> ВремяЗагрузки { get; set; }
        public Nullable<System.DateTime> ВремяОтправки { get; set; }
        public short Приоритет { get; set; }
    
        public virtual ICollection<ЗаданиеНаДоставку> ЗаданиеНаДоставку { get; set; }
        public virtual ICollection<НормАдр> НормАдр { get; set; }
    }
}
