//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх1ТаблДок
    {
        public Мх1ТаблДок()
        {
            this.Мх1ИтогТабл = new HashSet<Мх1ИтогТабл>();
            this.Мх1СтрТабл = new HashSet<Мх1СтрТабл>();
        }
    
        public string Название { get; set; }
        public string Тип { get; set; }
        public int ТаблДок_Id { get; set; }
        public Nullable<int> Документ_Id { get; set; }
    
        public virtual Мх1Документ Мх1Документ { get; set; }
        public virtual ICollection<Мх1ИтогТабл> Мх1ИтогТабл { get; set; }
        public virtual ICollection<Мх1СтрТабл> Мх1СтрТабл { get; set; }
    }
}
