//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх1Файл
    {
        public Мх1Файл()
        {
            this.Мх1Документ = new HashSet<Мх1Документ>();
        }
    
        public string ВерсПрог { get; set; }
        public string ВерсияФормата { get; set; }
        public string Имя { get; set; }
        public string Формат { get; set; }
        public string КодФормы { get; set; }
        public int Файл_Id { get; set; }
        public Nullable<int> ЗаказНаРазмещение_Документ_Id { get; set; }
        public int C_WfState { get; set; }
        public System.DateTime C_WfLastUpdateDT { get; set; }
        public bool C_Deleted { get; set; }
        public Nullable<System.DateTime> C_DeleteDT { get; set; }
        public string C_DeletedUser { get; set; }
        public string C_WfLastUpdateUser { get; set; }
    
        public virtual ICollection<Мх1Документ> Мх1Документ { get; set; }
    }
}
