//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх3Основание
    {
        public Мх3Основание()
        {
            this.Мх3Параметр = new HashSet<Мх3Параметр>();
        }
    
        public string Номер { get; set; }
        public string Дата { get; set; }
        public string КодОКВ { get; set; }
        public string Наим { get; set; }
        public Nullable<decimal> СуммаБезНал { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public string СрокОплаты { get; set; }
        public int Основание_Id { get; set; }
        public Nullable<int> Документ_Id { get; set; }
    
        public virtual Мх3Документ Мх3Документ { get; set; }
        public virtual ICollection<Мх3Параметр> Мх3Параметр { get; set; }
    }
}
