//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх1ИтогТабл
    {
        public Мх1ИтогТабл()
        {
            this.Мх1НДС = new HashSet<Мх1НДС>();
            this.Мх1Параметр = new HashSet<Мх1Параметр>();
            this.Мх1Характеристика = new HashSet<Мх1Характеристика>();
        }
    
        public string Тип { get; set; }
        public Nullable<decimal> Нетто { get; set; }
        public Nullable<decimal> СуммаБезНал { get; set; }
        public Nullable<int> Кол_во { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public int ИтогТабл_Id { get; set; }
        public Nullable<int> ТаблДок_Id { get; set; }
    
        public virtual Мх1ТаблДок Мх1ТаблДок { get; set; }
        public virtual ICollection<Мх1НДС> Мх1НДС { get; set; }
        public virtual ICollection<Мх1Параметр> Мх1Параметр { get; set; }
        public virtual ICollection<Мх1Характеристика> Мх1Характеристика { get; set; }
    }
}
