//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх1Основание
    {
        public Мх1Основание()
        {
            this.Мх1Параметр = new HashSet<Мх1Параметр>();
        }
    
        public string Номер { get; set; }
        public string Дата { get; set; }
        public string Наим { get; set; }
        public Nullable<float> СуммаБезНал { get; set; }
        public Nullable<float> Сумма { get; set; }
        public string Срок { get; set; }
        public int Основание_Id { get; set; }
        public Nullable<int> Документ_Id { get; set; }
    
        public virtual Мх1Документ Мх1Документ { get; set; }
        public virtual ICollection<Мх1Параметр> Мх1Параметр { get; set; }
    }
}
