//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх3Участник
    {
        public Мх3Участник()
        {
            this.Мх3Адрес = new HashSet<Мх3Адрес>();
            this.Мх3БанкРекв = new HashSet<Мх3БанкРекв>();
            this.Мх3Контакт = new HashSet<Мх3Контакт>();
            this.Мх3Параметр = new HashSet<Мх3Параметр>();
            this.Мх3Представитель = new HashSet<Мх3Представитель>();
            this.Мх3СвФЛ = new HashSet<Мх3СвФЛ>();
            this.Мх3СвЮЛ = new HashSet<Мх3СвЮЛ>();
        }
    
        public string Роль { get; set; }
        public int Участник_Id { get; set; }
        public Nullable<int> Документ_Id { get; set; }
    
        public virtual ICollection<Мх3Адрес> Мх3Адрес { get; set; }
        public virtual ICollection<Мх3БанкРекв> Мх3БанкРекв { get; set; }
        public virtual Мх3Документ Мх3Документ { get; set; }
        public virtual ICollection<Мх3Контакт> Мх3Контакт { get; set; }
        public virtual ICollection<Мх3Параметр> Мх3Параметр { get; set; }
        public virtual ICollection<Мх3Представитель> Мх3Представитель { get; set; }
        public virtual ICollection<Мх3СвФЛ> Мх3СвФЛ { get; set; }
        public virtual ICollection<Мх3СвЮЛ> Мх3СвЮЛ { get; set; }
    }
}
