//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх3Документ
    {
        public Мх3Документ()
        {
            this.Мх3Основание = new HashSet<Мх3Основание>();
            this.Мх3Параметр = new HashSet<Мх3Параметр>();
            this.Мх3Таблица = new HashSet<Мх3Таблица>();
            this.Мх3Участник = new HashSet<Мх3Участник>();
        }
    
        public string Дата { get; set; }
        public string Номер { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public string Примечание { get; set; }
        public int Документ_Id { get; set; }
        public Nullable<int> Файл_Id { get; set; }
    
        public virtual ICollection<Мх3Основание> Мх3Основание { get; set; }
        public virtual ICollection<Мх3Параметр> Мх3Параметр { get; set; }
        public virtual ICollection<Мх3Таблица> Мх3Таблица { get; set; }
        public virtual ICollection<Мх3Участник> Мх3Участник { get; set; }
        public virtual Мх3Файл Мх3Файл { get; set; }
    }
}
