//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх3Представитель
    {
        public Мх3Представитель()
        {
            this.Мх3СвФЛ = new HashSet<Мх3СвФЛ>();
        }
    
        public string Должность { get; set; }
        public string Роль { get; set; }
        public int Представитель_Id { get; set; }
        public Nullable<int> Участник_Id { get; set; }
    
        public virtual ICollection<Мх3СвФЛ> Мх3СвФЛ { get; set; }
        public virtual Мх3Участник Мх3Участник { get; set; }
    }
}
