//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх3Таблица
    {
        public Мх3Таблица()
        {
            this.Мх3ИтогТабл = new HashSet<Мх3ИтогТабл>();
            this.Мх3СтрТабл = new HashSet<Мх3СтрТабл>();
        }
    
        public string Тип { get; set; }
        public string Наим { get; set; }
        public int Таблица_Id { get; set; }
        public Nullable<int> Документ_Id { get; set; }
    
        public virtual Мх3Документ Мх3Документ { get; set; }
        public virtual ICollection<Мх3ИтогТабл> Мх3ИтогТабл { get; set; }
        public virtual ICollection<Мх3СтрТабл> Мх3СтрТабл { get; set; }
    }
}
