//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх1Отправитель
    {
        public Мх1Отправитель()
        {
            this.Мх1Адрес = new HashSet<Мх1Адрес>();
            this.Мх1Представитель = new HashSet<Мх1Представитель>();
            this.Мх1БанкРекв = new HashSet<Мх1БанкРекв>();
            this.Мх1Контакт = new HashSet<Мх1Контакт>();
            this.Мх1Параметр = new HashSet<Мх1Параметр>();
            this.Мх1Подразделение = new HashSet<Мх1Подразделение>();
            this.Мх1СвФЛ = new HashSet<Мх1СвФЛ>();
            this.Мх1СвЮЛ = new HashSet<Мх1СвЮЛ>();
        }
    
        public string Роль { get; set; }
        public string Название { get; set; }
        public int Отправитель_Id { get; set; }
        public Nullable<int> Документ_Id { get; set; }
    
        public virtual ICollection<Мх1Адрес> Мх1Адрес { get; set; }
        public virtual Мх1Документ Мх1Документ { get; set; }
        public virtual ICollection<Мх1Представитель> Мх1Представитель { get; set; }
        public virtual ICollection<Мх1БанкРекв> Мх1БанкРекв { get; set; }
        public virtual ICollection<Мх1Контакт> Мх1Контакт { get; set; }
        public virtual ICollection<Мх1Параметр> Мх1Параметр { get; set; }
        public virtual ICollection<Мх1Подразделение> Мх1Подразделение { get; set; }
        public virtual ICollection<Мх1СвФЛ> Мх1СвФЛ { get; set; }
        public virtual ICollection<Мх1СвЮЛ> Мх1СвЮЛ { get; set; }
    }
}
