//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх1Параметр
    {
        public string Имя { get; set; }
        public string Значение { get; set; }
        public Nullable<int> Основание_Id { get; set; }
        public Nullable<int> Отправитель_Id { get; set; }
        public Nullable<int> Получатель_Id { get; set; }
        public Nullable<int> ИтогТабл_Id { get; set; }
        public Nullable<int> Документ_Id { get; set; }
        public int Параметр_Id { get; set; }
    
        public virtual Мх1Документ Мх1Документ { get; set; }
        public virtual Мх1ИтогТабл Мх1ИтогТабл { get; set; }
        public virtual Мх1Основание Мх1Основание { get; set; }
        public virtual Мх1Отправитель Мх1Отправитель { get; set; }
        public virtual Мх1Получатель Мх1Получатель { get; set; }
    }
}
