//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх3Адрес
    {
        public Мх3Адрес()
        {
            this.Мх3АдрИно = new HashSet<Мх3АдрИно>();
            this.Мх3АдрРФ = new HashSet<Мх3АдрРФ>();
        }
    
        public string Тип { get; set; }
        public string Наим { get; set; }
        public int Адрес_Id { get; set; }
        public Nullable<int> Участник_Id { get; set; }
    
        public virtual ICollection<Мх3АдрИно> Мх3АдрИно { get; set; }
        public virtual ICollection<Мх3АдрРФ> Мх3АдрРФ { get; set; }
        public virtual Мх3Участник Мх3Участник { get; set; }
    }
}
