//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх3СвФЛ
    {
        public string ИНН { get; set; }
        public string Наим { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Обращение { get; set; }
        public Nullable<int> Представитель_Id { get; set; }
        public Nullable<int> Участник_Id { get; set; }
        public int СвФЛ_Id { get; set; }
    
        public virtual Мх3Представитель Мх3Представитель { get; set; }
        public virtual Мх3Участник Мх3Участник { get; set; }
    }
}
