//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мх1СтрТабл
    {
        public Мх1СтрТабл()
        {
            this.Мх1НДС = new HashSet<Мх1НДС>();
            this.Мх1Характеристика = new HashSet<Мх1Характеристика>();
        }
    
        public string ПорНомер { get; set; }
        public string Название { get; set; }
        public Nullable<int> Кол_во { get; set; }
        public string ЕдИзм { get; set; }
        public string ОКЕИ { get; set; }
        public string Код { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<decimal> СуммаБезНал { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public string Примечание { get; set; }
        public string Описание { get; set; }
        public int СтрТабл_Id { get; set; }
        public Nullable<int> ТаблДок_Id { get; set; }
    
        public virtual Мх1ТаблДок Мх1ТаблДок { get; set; }
        public virtual ICollection<Мх1НДС> Мх1НДС { get; set; }
        public virtual ICollection<Мх1Характеристика> Мх1Характеристика { get; set; }
    }
}
