//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class НормАдр
    {
        public НормАдр()
        {
            this.АктПриемкиАдрес = new HashSet<АктПриемкиАдрес>();
            this.ДоставкаАдрес = new HashSet<ДоставкаАдрес>();
            this.ЗаказНаОтгрузкуАдрес = new HashSet<ЗаказНаОтгрузкуАдрес>();
            this.ЗаказНаРазмещениеАдрес = new HashSet<ЗаказНаРазмещениеАдрес>();
            this.Мх1Адрес = new HashSet<Мх1Адрес>();
            this.Мх3Адрес = new HashSet<Мх3Адрес>();
        }
    
        public string АдрТекст { get; set; }
        public string Индекс { get; set; }
        public string КодРегион { get; set; }
        public string Район { get; set; }
        public string Город { get; set; }
        public string НаселПункт { get; set; }
        public string Улица { get; set; }
        public string Дом { get; set; }
        public string Корпус { get; set; }
        public string Кварт { get; set; }
        public System.Data.Spatial.DbGeography Коорд { get; set; }
        public string Ссылка { get; set; }
        public int НормАдр_Id { get; set; }
        public string Маршрут_Id { get; set; }
    
        public virtual ICollection<АктПриемкиАдрес> АктПриемкиАдрес { get; set; }
        public virtual ICollection<ДоставкаАдрес> ДоставкаАдрес { get; set; }
        public virtual ICollection<ЗаказНаОтгрузкуАдрес> ЗаказНаОтгрузкуАдрес { get; set; }
        public virtual ICollection<ЗаказНаРазмещениеАдрес> ЗаказНаРазмещениеАдрес { get; set; }
        public virtual Маршрут Маршрут { get; set; }
        public virtual ICollection<Мх1Адрес> Мх1Адрес { get; set; }
        public virtual ICollection<Мх3Адрес> Мх3Адрес { get; set; }
    }
}
