//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Перевозчик
    {
        public Перевозчик()
        {
            this.ЗаданиеНаДоставку = new HashSet<ЗаданиеНаДоставку>();
            this.Маршрут = new HashSet<Маршрут>();
        }
    
        public int Перевозчик_Id { get; set; }
        public bool Активен { get; set; }
        public string Название { get; set; }
        public string Тип { get; set; }
        public string Адрес { get; set; }
        public string ИНН { get; set; }
        public string КПП { get; set; }
        public string ОКДП { get; set; }
        public string ОКПО { get; set; }
        public string Тел { get; set; }
        public string Тел2 { get; set; }
        public string Факс { get; set; }
        public string Прмечание { get; set; }
        public string АвтоРегНомер { get; set; }
        public string АвтоМарка { get; set; }
        public Nullable<decimal> АвтоОбъем { get; set; }
        public Nullable<decimal> АвтоГрузоподъемность { get; set; }
    
        public virtual ICollection<ЗаданиеНаДоставку> ЗаданиеНаДоставку { get; set; }
        public virtual ICollection<Маршрут> Маршрут { get; set; }
    }
}
