//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public string Код { get; set; }
        public string ШтрихКод { get; set; }
        public string Название { get; set; }
        public string Производитель { get; set; }
        public string Примечание { get; set; }
        public decimal РазмерУпаковки_Ширина { get; set; }
        public decimal РазмерУпаковки_Длина { get; set; }
        public decimal РазмерУпаковки_Высота { get; set; }
        public decimal РазмерУпаковки_Вес { get; set; }
        public decimal РазмерКоробки_Ширина { get; set; }
        public decimal РазмерКоробки_Длина { get; set; }
        public decimal РазмерКоробки_Высота { get; set; }
        public decimal РазмерКоробки_Вес { get; set; }
        public int РазмерКоробки_Кол_воУп { get; set; }
        public decimal РазмерМалСтандарт_Ширина { get; set; }
        public decimal РазмерМалСтандарт_Длина { get; set; }
        public decimal РазмерМалСтандарт_Высота { get; set; }
        public decimal РазмерМалСтандарт_Вес { get; set; }
        public int РазмерМалСтандарт_Кол_воУп { get; set; }
        public int МинЗаказ { get; set; }
        public int КратнЗаказ { get; set; }
        public bool Пку { get; set; }
        public bool Стекло { get; set; }
        public string КлассОпасн { get; set; }
        public string ТемпРежим { get; set; }
        public string КодАВЕ { get; set; }
        public string КодНалСт { get; set; }
    }
}
