//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dme.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТТН
    {
        public ТТН()
        {
            this.ТТНСопрДок = new HashSet<ТТНСопрДок>();
        }
    
        public int ТТН_Id { get; set; }
        public int ЗаданиеНаДоставку_Id { get; set; }
        public string Номер { get; set; }
        public string Грузополучатель { get; set; }
        public string ГрузополучательАдрес { get; set; }
        public string ГрузополучательКонтакт { get; set; }
        public string Грузоотправитель { get; set; }
        public string ГрузоотправительАдрес { get; set; }
        public string ГрузоотправительКонтакт { get; set; }
        public string ГрузоотправительПрим1 { get; set; }
        public string ГрузоотправительПрим2 { get; set; }
        public string ГрузоотправительПрим3 { get; set; }
        public string НаимГруза { get; set; }
        public Nullable<int> Кол_воМест { get; set; }
        public string ВидУп { get; set; }
        public Nullable<decimal> Вес { get; set; }
        public Nullable<decimal> Объем { get; set; }
        public string ПриемГрузаАдрес { get; set; }
        public string ПриемГрузаВремя { get; set; }
        public string СдачаГрузаАдрес { get; set; }
        public string СдачаГрузаВремя { get; set; }
    
        public virtual ЗаданиеНаДоставку ЗаданиеНаДоставку { get; set; }
        public virtual ICollection<ТТНСопрДок> ТТНСопрДок { get; set; }
    }
}
